#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xc2ca9c8b, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x538bcbe4, __VMLINUX_SYMBOL_STR(seq_release_net) },
	{ 0xacc5e45, __VMLINUX_SYMBOL_STR(seq_read) },
	{ 0xa6bc24e9, __VMLINUX_SYMBOL_STR(seq_lseek) },
	{ 0xa89ae76c, __VMLINUX_SYMBOL_STR(sock_no_sendpage) },
	{ 0x8d39b20c, __VMLINUX_SYMBOL_STR(sock_no_mmap) },
	{ 0x8cddfaed, __VMLINUX_SYMBOL_STR(sock_no_getsockopt) },
	{ 0xb46965c6, __VMLINUX_SYMBOL_STR(sock_no_setsockopt) },
	{ 0xfd590737, __VMLINUX_SYMBOL_STR(sock_no_shutdown) },
	{ 0x4fe227c, __VMLINUX_SYMBOL_STR(sock_no_listen) },
	{ 0x4f74c167, __VMLINUX_SYMBOL_STR(sock_no_ioctl) },
	{ 0x3ef22c59, __VMLINUX_SYMBOL_STR(datagram_poll) },
	{ 0xe2ce02f0, __VMLINUX_SYMBOL_STR(sock_no_getname) },
	{ 0x7011dbb5, __VMLINUX_SYMBOL_STR(sock_no_accept) },
	{ 0x68c071d7, __VMLINUX_SYMBOL_STR(sock_no_socketpair) },
	{ 0x93ae7fbd, __VMLINUX_SYMBOL_STR(sock_no_connect) },
	{ 0xdb353d7a, __VMLINUX_SYMBOL_STR(sock_no_bind) },
	{ 0x80a4df04, __VMLINUX_SYMBOL_STR(xfrm_register_km) },
	{        0, __VMLINUX_SYMBOL_STR(sock_register) },
	{ 0x26ec25db, __VMLINUX_SYMBOL_STR(register_pernet_subsys) },
	{ 0x82dcd770, __VMLINUX_SYMBOL_STR(proto_register) },
	{ 0xf8cc038e, __VMLINUX_SYMBOL_STR(proto_unregister) },
	{ 0xdcc6aefd, __VMLINUX_SYMBOL_STR(unregister_pernet_subsys) },
	{ 0x62737e1d, __VMLINUX_SYMBOL_STR(sock_unregister) },
	{ 0xdd6e0324, __VMLINUX_SYMBOL_STR(xfrm_unregister_km) },
	{ 0x5ef0cb31, __VMLINUX_SYMBOL_STR(init_net) },
	{ 0x7a8ca627, __VMLINUX_SYMBOL_STR(xfrm_count_pfkey_enc_supported) },
	{ 0xa575945, __VMLINUX_SYMBOL_STR(xfrm_count_pfkey_auth_supported) },
	{ 0x28e23139, __VMLINUX_SYMBOL_STR(xfrm_probe_algs) },
	{ 0xe60c12e1, __VMLINUX_SYMBOL_STR(xfrm_audit_policy_add) },
	{ 0x9b0f5040, __VMLINUX_SYMBOL_STR(xfrm_policy_insert) },
	{ 0xd0f04810, __VMLINUX_SYMBOL_STR(xfrm_policy_alloc) },
	{ 0xe5ed5467, __VMLINUX_SYMBOL_STR(xfrm_policy_walk_init) },
	{ 0xc2b06344, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xbc8b0f41, __VMLINUX_SYMBOL_STR(xfrm_calg_get_byid) },
	{ 0x92dbc6c1, __VMLINUX_SYMBOL_STR(xfrm_aalg_get_byid) },
	{ 0x1d7b6ae0, __VMLINUX_SYMBOL_STR(xfrm_init_state) },
	{ 0x65e59da8, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0xe914e41e, __VMLINUX_SYMBOL_STR(strcpy) },
	{ 0xce7a55c1, __VMLINUX_SYMBOL_STR(xfrm_ealg_get_byid) },
	{ 0x65f36bdf, __VMLINUX_SYMBOL_STR(xfrm_state_add) },
	{ 0x29e48f1, __VMLINUX_SYMBOL_STR(xfrm_audit_state_add) },
	{ 0xc98b8d30, __VMLINUX_SYMBOL_STR(xfrm_state_update) },
	{ 0x27866435, __VMLINUX_SYMBOL_STR(security_xfrm_state_alloc) },
	{ 0xe24d9b6, __VMLINUX_SYMBOL_STR(xfrm_state_alloc) },
	{ 0xa9c63b69, __VMLINUX_SYMBOL_STR(security_xfrm_policy_free) },
	{ 0x91631de0, __VMLINUX_SYMBOL_STR(xfrm_policy_bysel_ctx) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xb15cb614, __VMLINUX_SYMBOL_STR(security_xfrm_policy_alloc) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xcc48ad1b, __VMLINUX_SYMBOL_STR(xfrm_migrate) },
	{ 0x26a534d0, __VMLINUX_SYMBOL_STR(xfrm_alloc_spi) },
	{ 0xf10526ac, __VMLINUX_SYMBOL_STR(verify_spi_info) },
	{ 0x7cba7164, __VMLINUX_SYMBOL_STR(xfrm_find_acq) },
	{ 0x778770, __VMLINUX_SYMBOL_STR(xfrm_ealg_get_byname) },
	{ 0x7c30b8c7, __VMLINUX_SYMBOL_STR(xfrm_calg_get_byname) },
	{ 0xe122af95, __VMLINUX_SYMBOL_STR(xfrm_aalg_get_byname) },
	{ 0x56bb269, __VMLINUX_SYMBOL_STR(xfrm_ealg_get_byidx) },
	{ 0x74e1a843, __VMLINUX_SYMBOL_STR(xfrm_aalg_get_byidx) },
	{ 0x2ddd3e86, __VMLINUX_SYMBOL_STR(xfrm_garbage_collect) },
	{ 0x300bdd4, __VMLINUX_SYMBOL_STR(xfrm_policy_destroy) },
	{ 0xc339404e, __VMLINUX_SYMBOL_STR(xfrm_audit_policy_delete) },
	{ 0x8de447b7, __VMLINUX_SYMBOL_STR(xfrm_policy_byid) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x1e9edfb7, __VMLINUX_SYMBOL_STR(seq_hlist_start_head_rcu) },
	{ 0x67b78eb3, __VMLINUX_SYMBOL_STR(seq_hlist_next_rcu) },
	{ 0x3a65ed9f, __VMLINUX_SYMBOL_STR(remove_proc_entry) },
	{ 0xb3b3c4f4, __VMLINUX_SYMBOL_STR(proc_create_data) },
	{ 0x91391cfd, __VMLINUX_SYMBOL_STR(xfrm_state_delete) },
	{ 0x8a15f279, __VMLINUX_SYMBOL_STR(xfrm_audit_state_delete) },
	{ 0xc599a772, __VMLINUX_SYMBOL_STR(security_xfrm_state_delete) },
	{ 0xc2cdbf1, __VMLINUX_SYMBOL_STR(synchronize_sched) },
	{ 0xc0056be5, __VMLINUX_SYMBOL_STR(_raw_write_unlock_bh) },
	{ 0x6ec9ccdb, __VMLINUX_SYMBOL_STR(_raw_write_lock_bh) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xaaf11b11, __VMLINUX_SYMBOL_STR(skb_queue_purge) },
	{ 0x934e86cc, __VMLINUX_SYMBOL_STR(xfrm_state_lookup) },
	{ 0x3e2dda84, __VMLINUX_SYMBOL_STR(__xfrm_state_destroy) },
	{ 0xdd3916ac, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_bh) },
	{ 0xa1d55e90, __VMLINUX_SYMBOL_STR(_raw_spin_lock_bh) },
	{ 0xfd3315af, __VMLINUX_SYMBOL_STR(xfrm_find_acq_byseq) },
	{ 0x5ad328f5, __VMLINUX_SYMBOL_STR(km_state_notify) },
	{ 0xd5280962, __VMLINUX_SYMBOL_STR(xfrm_state_flush) },
	{ 0x76255cb9, __VMLINUX_SYMBOL_STR(xfrm_state_walk) },
	{ 0x70a6dfff, __VMLINUX_SYMBOL_STR(xfrm_state_walk_done) },
	{ 0x51dce73b, __VMLINUX_SYMBOL_STR(xfrm_state_walk_init) },
	{ 0xb622c2cd, __VMLINUX_SYMBOL_STR(skb_copy) },
	{ 0xd9962a92, __VMLINUX_SYMBOL_STR(km_policy_notify) },
	{ 0x20c9ee5, __VMLINUX_SYMBOL_STR(xfrm_policy_flush) },
	{ 0x6970534a, __VMLINUX_SYMBOL_STR(sock_init_data) },
	{ 0xafd7e350, __VMLINUX_SYMBOL_STR(sk_alloc) },
	{        0, __VMLINUX_SYMBOL_STR(ns_capable) },
	{ 0xf4b6d3b1, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x1e31c3d, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x9fb3dd30, __VMLINUX_SYMBOL_STR(memcpy_fromiovec) },
	{ 0xe37d87c3, __VMLINUX_SYMBOL_STR(__sock_recv_ts_and_drops) },
	{ 0x8389bb64, __VMLINUX_SYMBOL_STR(skb_free_datagram) },
	{ 0xad1ea416, __VMLINUX_SYMBOL_STR(skb_copy_datagram_iovec) },
	{ 0x29e41014, __VMLINUX_SYMBOL_STR(skb_recv_datagram) },
	{ 0x9c7b7e44, __VMLINUX_SYMBOL_STR(xfrm_policy_walk_done) },
	{ 0xa673bb44, __VMLINUX_SYMBOL_STR(xfrm_policy_walk) },
	{ 0xca6b6169, __VMLINUX_SYMBOL_STR(skb_put) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0x6122b44b, __VMLINUX_SYMBOL_STR(sock_rfree) },
	{ 0x16053804, __VMLINUX_SYMBOL_STR(skb_clone) },
	{ 0xc502e7fe, __VMLINUX_SYMBOL_STR(sk_free) },
	{ 0x3b99b8aa, __VMLINUX_SYMBOL_STR(skb_queue_tail) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0xc848f815, __VMLINUX_SYMBOL_STR(__alloc_skb) },
	{ 0x69a4507f, __VMLINUX_SYMBOL_STR(kfree_skb) },
	{ 0x22675997, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x22bbd80b, __VMLINUX_SYMBOL_STR(sock_i_ino) },
	{ 0x409cf9dd, __VMLINUX_SYMBOL_STR(from_kuid_munged) },
	{ 0xcecbd3d5, __VMLINUX_SYMBOL_STR(sock_i_uid) },
	{ 0xbb4e6169, __VMLINUX_SYMBOL_STR(seq_open_net) },
	{ 0xefd6cf06, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr0) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=";


MODULE_INFO(srcversion, "C94972D94F40A38D512BE3A");
