#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xc2ca9c8b, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xbaff3a71, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0xc2b06344, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x7e083135, __VMLINUX_SYMBOL_STR(ata_std_prereset) },
	{ 0x8d316b9a, __VMLINUX_SYMBOL_STR(ata_port_wait_eh) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xf9a482f9, __VMLINUX_SYMBOL_STR(msleep) },
	{ 0xd0a49a39, __VMLINUX_SYMBOL_STR(sas_remove_children) },
	{ 0xda8c5ad7, __VMLINUX_SYMBOL_STR(sas_release_transport) },
	{ 0xa532c30d, __VMLINUX_SYMBOL_STR(blk_queue_free_tags) },
	{ 0x49daed98, __VMLINUX_SYMBOL_STR(scsi_track_queue_full) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0xc996d097, __VMLINUX_SYMBOL_STR(del_timer) },
	{ 0xfa3ec1e7, __VMLINUX_SYMBOL_STR(page_address) },
	{ 0x5647314f, __VMLINUX_SYMBOL_STR(blk_abort_request) },
	{ 0xc901afb4, __VMLINUX_SYMBOL_STR(scsi_block_requests) },
	{ 0x7637f31f, __VMLINUX_SYMBOL_STR(ata_std_sched_eh) },
	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0x8712734b, __VMLINUX_SYMBOL_STR(sas_port_free) },
	{ 0xd6195785, __VMLINUX_SYMBOL_STR(dev_printk) },
	{ 0xeafeb1e5, __VMLINUX_SYMBOL_STR(sas_phy_add) },
	{ 0xbcabbce0, __VMLINUX_SYMBOL_STR(scsi_unblock_requests) },
	{ 0x7d6fb3b1, __VMLINUX_SYMBOL_STR(ata_sas_slave_configure) },
	{ 0xa177a4ca, __VMLINUX_SYMBOL_STR(ata_scsi_cmd_error_handler) },
	{ 0x55a277e5, __VMLINUX_SYMBOL_STR(sas_port_add_phy) },
	{ 0x2a3aa678, __VMLINUX_SYMBOL_STR(_test_and_clear_bit) },
	{ 0xd5152710, __VMLINUX_SYMBOL_STR(sg_next) },
	{ 0x9008015a, __VMLINUX_SYMBOL_STR(sas_rphy_free) },
	{ 0x593a99b, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0xf4b6d3b1, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x7dae9cb2, __VMLINUX_SYMBOL_STR(sas_port_delete_phy) },
	{ 0x85c4a705, __VMLINUX_SYMBOL_STR(sas_rphy_add) },
	{ 0x8ad9e73b, __VMLINUX_SYMBOL_STR(ata_sas_port_suspend) },
	{ 0xe8d3f133, __VMLINUX_SYMBOL_STR(ata_sas_port_init) },
	{ 0xc8f01ab, __VMLINUX_SYMBOL_STR(scsi_adjust_queue_depth) },
	{ 0x5e7f1231, __VMLINUX_SYMBOL_STR(kthread_create_on_node) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x1f2429e5, __VMLINUX_SYMBOL_STR(sas_port_delete) },
	{ 0x96535b39, __VMLINUX_SYMBOL_STR(ata_sas_async_probe) },
	{ 0x275ef902, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x73be263e, __VMLINUX_SYMBOL_STR(sas_attach_transport) },
	{ 0x1fab5905, __VMLINUX_SYMBOL_STR(wait_for_completion) },
	{ 0x1746a1f2, __VMLINUX_SYMBOL_STR(kmap_atomic) },
	{ 0xe21cc54f, __VMLINUX_SYMBOL_STR(scsi_is_host_device) },
	{ 0x20a57bb4, __VMLINUX_SYMBOL_STR(sas_rphy_delete) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0x11262acc, __VMLINUX_SYMBOL_STR(ata_sas_port_stop) },
	{ 0xcded1c35, __VMLINUX_SYMBOL_STR(scsi_queue_work) },
	{ 0x647f89c5, __VMLINUX_SYMBOL_STR(sas_expander_alloc) },
	{ 0x11089ac7, __VMLINUX_SYMBOL_STR(_ctype) },
	{ 0x51d559d1, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0xe304147c, __VMLINUX_SYMBOL_STR(sas_read_port_mode_page) },
	{ 0x5ab2090c, __VMLINUX_SYMBOL_STR(mutex_lock_interruptible) },
	{ 0xe30a859f, __VMLINUX_SYMBOL_STR(sas_end_device_alloc) },
	{ 0xe15f9d39, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xf57a0b7f, __VMLINUX_SYMBOL_STR(kthread_stop) },
	{ 0x71c90087, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x602559bf, __VMLINUX_SYMBOL_STR(ata_std_error_handler) },
	{ 0x8a530118, __VMLINUX_SYMBOL_STR(ata_scsi_port_error_handler) },
	{ 0x1e5aa471, __VMLINUX_SYMBOL_STR(ata_sas_port_start) },
	{ 0x45c48b49, __VMLINUX_SYMBOL_STR(ata_std_qc_defer) },
	{ 0xcea75b8e, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0xd12b154e, __VMLINUX_SYMBOL_STR(sas_port_mark_backlink) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x1e31c3d, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xed93f29e, __VMLINUX_SYMBOL_STR(__kunmap_atomic) },
	{ 0x8f2afc0d, __VMLINUX_SYMBOL_STR(sas_port_add) },
	{ 0xbe2c0274, __VMLINUX_SYMBOL_STR(add_timer) },
	{ 0xf811e69d, __VMLINUX_SYMBOL_STR(scsi_eh_flush_done_q) },
	{ 0xf17fb249, __VMLINUX_SYMBOL_STR(ata_port_schedule_eh) },
	{ 0xb1c0c1c2, __VMLINUX_SYMBOL_STR(async_schedule_domain) },
	{ 0x146ea289, __VMLINUX_SYMBOL_STR(ata_sas_port_alloc) },
	{ 0xb0bda803, __VMLINUX_SYMBOL_STR(ata_noop_qc_prep) },
	{ 0xb6c4b184, __VMLINUX_SYMBOL_STR(scsi_eh_finish_cmd) },
	{ 0xcbcd255d, __VMLINUX_SYMBOL_STR(sas_phy_free) },
	{ 0xbaa88862, __VMLINUX_SYMBOL_STR(_dev_info) },
	{ 0x65e59da8, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x57f1623f, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0x3bd1b1f6, __VMLINUX_SYMBOL_STR(msecs_to_jiffies) },
	{ 0x6cd21997, __VMLINUX_SYMBOL_STR(ata_tf_to_fis) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0x3507a132, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irq) },
	{ 0xa6707bf1, __VMLINUX_SYMBOL_STR(sas_phy_alloc) },
	{ 0x1031f1dc, __VMLINUX_SYMBOL_STR(wake_up_process) },
	{ 0x31bb5284, __VMLINUX_SYMBOL_STR(ata_wait_after_reset) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x598542b2, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x6703f64a, __VMLINUX_SYMBOL_STR(get_device) },
	{ 0x96b6f4b8, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0x26c90ea4, __VMLINUX_SYMBOL_STR(scsi_eh_get_sense) },
	{ 0xd85cd67e, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0xb3f7646e, __VMLINUX_SYMBOL_STR(kthread_should_stop) },
	{ 0x344b7739, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0xea10212a, __VMLINUX_SYMBOL_STR(int_to_scsilun) },
	{ 0xefdd2345, __VMLINUX_SYMBOL_STR(sg_init_one) },
	{ 0x798cbe01, __VMLINUX_SYMBOL_STR(ata_sas_port_resume) },
	{ 0x57a055ca, __VMLINUX_SYMBOL_STR(blk_queue_init_tags) },
	{ 0x98779b60, __VMLINUX_SYMBOL_STR(sas_port_get_phy) },
	{ 0x9c55cec, __VMLINUX_SYMBOL_STR(schedule_timeout_interruptible) },
	{ 0x682a4420, __VMLINUX_SYMBOL_STR(scsi_eh_ready_devs) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x6ca4bf88, __VMLINUX_SYMBOL_STR(async_synchronize_full_domain) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x9304b6, __VMLINUX_SYMBOL_STR(ata_tf_from_fis) },
	{ 0x499cb58c, __VMLINUX_SYMBOL_STR(prepare_to_wait) },
	{ 0xb9886361, __VMLINUX_SYMBOL_STR(sas_port_alloc) },
	{ 0x4994bd5a, __VMLINUX_SYMBOL_STR(ata_host_init) },
	{ 0xd2a51709, __VMLINUX_SYMBOL_STR(flush_kernel_dcache_page) },
	{ 0x55dd9e75, __VMLINUX_SYMBOL_STR(request_firmware) },
	{ 0xfeb4fc68, __VMLINUX_SYMBOL_STR(scsi_schedule_eh) },
	{ 0x1cfb04fa, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0xf629e1be, __VMLINUX_SYMBOL_STR(dev_warn) },
	{ 0xe4339817, __VMLINUX_SYMBOL_STR(ata_std_postreset) },
	{ 0xefd6cf06, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr0) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0xa615c689, __VMLINUX_SYMBOL_STR(sas_rphy_unlink) },
	{ 0xd4669fad, __VMLINUX_SYMBOL_STR(complete) },
	{ 0xca54fee, __VMLINUX_SYMBOL_STR(_test_and_set_bit) },
	{ 0x977cc8ab, __VMLINUX_SYMBOL_STR(ata_sas_queuecmd) },
	{ 0xda90028e, __VMLINUX_SYMBOL_STR(ata_sas_port_destroy) },
	{ 0xa38602cd, __VMLINUX_SYMBOL_STR(drain_workqueue) },
	{ 0x49ebacbd, __VMLINUX_SYMBOL_STR(_clear_bit) },
	{ 0x49cd3891, __VMLINUX_SYMBOL_STR(sas_rphy_remove) },
	{ 0x61050c4d, __VMLINUX_SYMBOL_STR(outer_cache) },
	{ 0x32e8f353, __VMLINUX_SYMBOL_STR(release_firmware) },
	{ 0x93ab4dde, __VMLINUX_SYMBOL_STR(ata_sas_scsi_ioctl) },
	{ 0x7364f840, __VMLINUX_SYMBOL_STR(__ata_change_queue_depth) },
	{ 0x29755f0c, __VMLINUX_SYMBOL_STR(ata_qc_complete) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=scsi_transport_sas";


MODULE_INFO(srcversion, "506307F5E21EF5A67512539");
