#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xc2ca9c8b, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x59715c6d, __VMLINUX_SYMBOL_STR(vfs_create) },
	{ 0x2110e30d, __VMLINUX_SYMBOL_STR(set_create_files_as) },
	{ 0xbaff3a71, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0xc2b06344, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x405c1144, __VMLINUX_SYMBOL_STR(get_seconds) },
	{ 0x6c5398aa, __VMLINUX_SYMBOL_STR(set_security_override_from_ctx) },
	{ 0x6da4785a, __VMLINUX_SYMBOL_STR(security_inode_mkdir) },
	{ 0xfbc74f64, __VMLINUX_SYMBOL_STR(__copy_from_user) },
	{ 0x2b8c46d1, __VMLINUX_SYMBOL_STR(up_read) },
	{ 0x349cba85, __VMLINUX_SYMBOL_STR(strchr) },
	{ 0x67c2fa54, __VMLINUX_SYMBOL_STR(__copy_to_user) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0xa0fbac79, __VMLINUX_SYMBOL_STR(wake_up_bit) },
	{ 0x97255bdf, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x3a4a9aab, __VMLINUX_SYMBOL_STR(prepare_kernel_cred) },
	{ 0x463dcfd7, __VMLINUX_SYMBOL_STR(dget_parent) },
	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0xa43403b6, __VMLINUX_SYMBOL_STR(pagecache_get_page) },
	{ 0xb5198b77, __VMLINUX_SYMBOL_STR(_raw_read_lock) },
	{ 0x20000329, __VMLINUX_SYMBOL_STR(simple_strtoul) },
	{ 0xb783829, __VMLINUX_SYMBOL_STR(touch_atime) },
	{ 0xbdac1eb7, __VMLINUX_SYMBOL_STR(lockref_get) },
	{ 0x1033ac04, __VMLINUX_SYMBOL_STR(dput) },
	{ 0x2a3aa678, __VMLINUX_SYMBOL_STR(_test_and_clear_bit) },
	{ 0x7c04c596, __VMLINUX_SYMBOL_STR(dentry_open) },
	{ 0x4ee6b1f5, __VMLINUX_SYMBOL_STR(fscache_object_init) },
	{ 0xf4b6d3b1, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x52e92aab, __VMLINUX_SYMBOL_STR(fscache_object_lookup_negative) },
	{ 0x2aacdde6, __VMLINUX_SYMBOL_STR(path_get) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0x5fef27a9, __VMLINUX_SYMBOL_STR(fscache_add_cache) },
	{ 0x90987cfb, __VMLINUX_SYMBOL_STR(fscache_check_aux) },
	{ 0x6c8e261a, __VMLINUX_SYMBOL_STR(override_creds) },
	{ 0xad188e4f, __VMLINUX_SYMBOL_STR(__alloc_pages_nodemask) },
	{ 0xa11f250e, __VMLINUX_SYMBOL_STR(security_inode_create) },
	{ 0xc499ae1e, __VMLINUX_SYMBOL_STR(kstrdup) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x7b0564fd, __VMLINUX_SYMBOL_STR(lru_cache_add_file) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0x114c7607, __VMLINUX_SYMBOL_STR(down_read) },
	{ 0x5fa42ebb, __VMLINUX_SYMBOL_STR(unlock_rename) },
	{ 0x25631afd, __VMLINUX_SYMBOL_STR(fscache_cache_cleared_wq) },
	{ 0x275ef902, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x1746a1f2, __VMLINUX_SYMBOL_STR(kmap_atomic) },
	{ 0xddca91a9, __VMLINUX_SYMBOL_STR(misc_register) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0xe5996ba5, __VMLINUX_SYMBOL_STR(kern_path) },
	{ 0x11089ac7, __VMLINUX_SYMBOL_STR(_ctype) },
	{ 0xe15f9d39, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x4d602904, __VMLINUX_SYMBOL_STR(fscache_obtained_object) },
	{ 0x6abe4e61, __VMLINUX_SYMBOL_STR(kunmap) },
	{ 0x8b12500, __VMLINUX_SYMBOL_STR(vfs_getxattr) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0x4d9b652b, __VMLINUX_SYMBOL_STR(rb_erase) },
	{ 0xcea75b8e, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x66f34acf, __VMLINUX_SYMBOL_STR(lock_rename) },
	{ 0x1e31c3d, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xd100acbd, __VMLINUX_SYMBOL_STR(_raw_write_lock) },
	{ 0xed93f29e, __VMLINUX_SYMBOL_STR(__kunmap_atomic) },
	{ 0x561ea89b, __VMLINUX_SYMBOL_STR(noop_llseek) },
	{ 0xe0bb0556, __VMLINUX_SYMBOL_STR(fscache_withdraw_cache) },
	{ 0xdd27fa87, __VMLINUX_SYMBOL_STR(memchr) },
	{ 0xa0a2e9c9, __VMLINUX_SYMBOL_STR(unlock_page) },
	{ 0x3c34b874, __VMLINUX_SYMBOL_STR(fput) },
	{ 0x8522d53f, __VMLINUX_SYMBOL_STR(__get_page_tail) },
	{ 0x1f5ee312, __VMLINUX_SYMBOL_STR(fscache_mark_pages_cached) },
	{ 0xcadd71d4, __VMLINUX_SYMBOL_STR(fscache_mark_page_cached) },
	{ 0x96ec6ba8, __VMLINUX_SYMBOL_STR(contig_page_data) },
	{ 0xacdc7916, __VMLINUX_SYMBOL_STR(prepare_creds) },
	{ 0xa1f0ebea, __VMLINUX_SYMBOL_STR(bit_waitqueue) },
	{ 0x632780, __VMLINUX_SYMBOL_STR(work_busy) },
	{ 0x4c94f620, __VMLINUX_SYMBOL_STR(mntput) },
	{ 0x783b3563, __VMLINUX_SYMBOL_STR(wake_up_atomic_t) },
	{ 0xc6cbbc89, __VMLINUX_SYMBOL_STR(capable) },
	{ 0x65e59da8, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x4d0d163d, __VMLINUX_SYMBOL_STR(copy_page) },
	{ 0x39cf8e1e, __VMLINUX_SYMBOL_STR(kmap) },
	{ 0x369dbf62, __VMLINUX_SYMBOL_STR(fscache_init_cache) },
	{ 0x339b7cff, __VMLINUX_SYMBOL_STR(fscache_object_destroy) },
	{ 0x3507a132, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irq) },
	{ 0x6ee11911, __VMLINUX_SYMBOL_STR(vfs_statfs) },
	{ 0xf758af4, __VMLINUX_SYMBOL_STR(vfs_mkdir) },
	{ 0x4c25829a, __VMLINUX_SYMBOL_STR(__put_cred) },
	{ 0x582eff05, __VMLINUX_SYMBOL_STR(path_put) },
	{ 0x8dc3a8e1, __VMLINUX_SYMBOL_STR(vfs_truncate) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0xb5af9773, __VMLINUX_SYMBOL_STR(fscache_put_operation) },
	{ 0xa5526619, __VMLINUX_SYMBOL_STR(rb_insert_color) },
	{ 0xb0742bb3, __VMLINUX_SYMBOL_STR(vfs_unlink) },
	{ 0x96b6f4b8, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0xd85cd67e, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x42b5e345, __VMLINUX_SYMBOL_STR(add_to_page_cache_locked) },
	{ 0xf584caac, __VMLINUX_SYMBOL_STR(add_page_wait_queue) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xbd8b4bdf, __VMLINUX_SYMBOL_STR(__sb_end_write) },
	{ 0x499cb58c, __VMLINUX_SYMBOL_STR(prepare_to_wait) },
	{ 0x721b1851, __VMLINUX_SYMBOL_STR(skip_spaces) },
	{ 0x609f223f, __VMLINUX_SYMBOL_STR(sync_filesystem) },
	{ 0xfe0a4c21, __VMLINUX_SYMBOL_STR(fscache_io_error) },
	{ 0x18cc549c, __VMLINUX_SYMBOL_STR(abort_creds) },
	{ 0xbb75660d, __VMLINUX_SYMBOL_STR(__sb_start_write) },
	{ 0x93ae4026, __VMLINUX_SYMBOL_STR(put_page) },
	{ 0x1cfb04fa, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0xefd6cf06, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr0) },
	{ 0x92cf98e, __VMLINUX_SYMBOL_STR(fscache_object_sleep_till_congested) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0xb81960ca, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0xca54fee, __VMLINUX_SYMBOL_STR(_test_and_set_bit) },
	{ 0xccbd1405, __VMLINUX_SYMBOL_STR(fscache_enqueue_operation) },
	{ 0x42bc397c, __VMLINUX_SYMBOL_STR(lookup_one_len) },
	{ 0xdd387c4e, __VMLINUX_SYMBOL_STR(vfs_rename) },
	{ 0x49ebacbd, __VMLINUX_SYMBOL_STR(_clear_bit) },
	{ 0x7ba81fe, __VMLINUX_SYMBOL_STR(fscache_op_complete) },
	{ 0x47c8baf4, __VMLINUX_SYMBOL_STR(param_ops_uint) },
	{ 0x4ac041fc, __VMLINUX_SYMBOL_STR(notify_change) },
	{ 0x9ea3aebc, __VMLINUX_SYMBOL_STR(vfs_setxattr) },
	{ 0x73d004e8, __VMLINUX_SYMBOL_STR(misc_deregister) },
	{ 0x22d68b42, __VMLINUX_SYMBOL_STR(revert_creds) },
	{ 0x4ccec4d2, __VMLINUX_SYMBOL_STR(vfs_removexattr) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=fscache";


MODULE_INFO(srcversion, "8B9FA64A325D8FA439CA41C");
